### ISSUE TITLE
Cannot find module '#imports' 

### ISSUE THREAD

**Issue by mrleblanc101** [itpropro/nuxt-oidc-auth#6] opened 2024-01-17 21:43 UTC
Just saw there has been some update since this morning, so I was trying the latest 0.9.10 and got this error:
> Error while requiring module nuxt-oidc-auth: Error: Cannot find module '#imports' 
Require stack:
> - /Users/sleblanc/www/nuxt-3-keycloak-auth/node_modules/nuxt-oidc-auth/dist/module.mjs

**Comment by itpropro** [comment] 2024-01-17 23:36
Hey,
Is fixed with the latest release. Was caused by updated deps resolving with new nuxt version.

**Closed by itpropro** 2024-01-17 23:36 UTC
