### ISSUE TITLE
Own WSO2 integration doesnt login

### ISSUE THREAD

**Issue by agracia-foticos** [itpropro/nuxt-oidc-auth#39] opened 2024-06-27 06:29 UTC
We want to implement login with own WSO2 platform.

We press the button
![image](https://github.com/itpropro/nuxt-oidc-auth/assets/77386602/5397dff1-630d-4374-bf53-c625a0f59658)

Goes to our WSO2 and loggin in it
![image](https://github.com/itpropro/nuxt-oidc-auth/assets/77386602/563da517-417a-4fd0-b35d-b7d8cb832f54)

and returns with query params
![image](https://github.com/itpropro/nuxt-oidc-auth/assets/77386602/c63a6b90-44cb-4d5a-91ac-42dd2edbff47)

But the variable loggedIn in useOidcAuth its false

we have a cookie
![image](https://github.com/itpropro/nuxt-oidc-auth/assets/77386602/c654097c-b4fc-484e-9fb5-1e26acfd4f34)

**Comment by itpropro** [comment] 2024-08-28 22:55
It seems like you haven't configured the callback correctly. Please check if the callback url is configured correctly and if you are still logged in after a refresh.

**Comment by itpropro** [comment] 2024-08-28 23:01
Duplicate of #37

**Closed by itpropro** 2024-08-28 23:01 UTC
