### ISSUE TITLE
Unable to use custom providers with versions after 0.15

### ISSUE THREAD

**Issue by TonyArntsen** [itpropro/nuxt-oidc-auth#63] opened 2024-10-02 10:54 UTC
I am unable to use custom providers in my Nuxt project with versions after 0.15.0.
In 0.16.0 and up, the module only works with preset providers such as github, etc.
I had to revert back to 0.15.0 to keep my OIDC configuration working as it was.

## Explanation

After updating to the latest version, 0.18.0, the **nuxt.config.ts** configuration has linter errors within the oidc{} object

`  oidc: {
    defaultProvider: "MyProvider",
    providers: {
      MyProvider: {`

The linter in this example will not accept defaultProvider as a property, neither the generic MyProvider property, and mark them with errors.

When trying to run the project, this error appears:
`Cannot read properties of undefined (reading 'additionalAuthParameters') `
_Same error when using **npm install** (pnpm has same issues) after bumping up to latest version._

It is possible that the expected configuration for this module has changed, but this is not reflected in any documentation found online.

## Reproduce

Steps to reproduce: Try to make a custom provider, based on the current documentation, using version from 0.16.0 and up.

Documentation from the offical page:
`export default defineNuxtConfig({
  oidc: {
    defaultProvider: '<provider>',
    providers: {
      <provider>: {
        clientId: '...',
        clientSecret: '...'
      }
    },
    middleware: {
      globalMiddlewareEnabled: true,
      customLoginPage: false
    }
  }
})`

**Comment by itpropro** [comment] 2024-10-03 20:20
I was not able to reproduce this, I use custom providers in multiple production deployments, can you provide a reproduction repository including your identity providers config please?
Also which IdP are you using, maybe we can create a custom provider to make it easier to use.

**Comment by christianOB** [comment] 2024-10-03 22:18
Seems like to use the custom oidc, you must use the actual key `oidc` not `MyProvider`: 
```
oidc: {
    defaultProvider: 'oidc',
    providers: {
      oidc: {
           ....
      }
    }
  },
```

**Comment by itpropro** [comment] 2024-10-04 00:16
Correct. The key for the custom oidc provider in case there is no provider for yours is `oidc`.

**Comment by itpropro** [comment] 2024-10-04 14:03
I will close this issue for now, it would be great if you could add a issue to request your Identity Provider as a preset, so you don't have to use the `oidc` key.

**Closed by itpropro** 2024-10-04 14:03 UTC
Labels: pending triage, needs reproduction
